### ISSUE TITLE
Spine not rendering when hidden.

### ISSUE THREAD

**Issue by PonyOny** [Reltdeats/spine-phaser-ce#1]
I have noticed that when spine elements are hidden or not visible on initial loading, bounds are not calculated properly, this results in spine not being displayed on scene, if rendering is forced spine shows properly.

**Comment by Reltdeats** [comment]
Correct, for now all the spine elements have to be visible by default so that the plugin can calculate the render bounds.

I'm going to look for a viable alternative that doesn't affect performance too much.

**Comment by Reltdeats** [comment]
I've added default render bounds generation when there is no default setup pose to fix this bug, while I look into better solutions. For now, performance wise, this is the better solution.

Anyway, its a good practice to add a visible default setup pose to the Spine, or you will get strange behaviour even on the official plugins.

To get this fix, update to the latest version.
